import { SimulatorResult } from "../types";

export const initialSimulatorResult: SimulatorResult = {
  tipoSimulacao: "financiado",
  valorArrematacao: 0,
  valorVenda: 0,
  itbi: 0,
  comissaoLeiloeiro: 0,
  comissaoCorretor: 0,
  valorIR: 0,
  porcEntradaFinanciamento: 0,
  valorEntradaFinanciamento: 0,
  porcFinanciamento: 0,
  valorFinanciamento: 0,
  prazoFinanciamento: 0,
  taxaJurosAnual: 0,
  taxaJurosMensal: 0,
  valorComissaoLeiloeiro: 0,
  valorITBI: 0,
  registroImovel: 0,
  valorDesocupacao: 0,
  valorReformas: 0,
  valorOutrosGastos: 0,
  totalCustosParciais: 0,
  prazoVenda: 0,
  iptuMensal: 0,
  totalIptu: 0,
  condominioMensal: 0,
  totalCondominio: 0,  
  totalCustosAteVenda: 0,
  valorComissaoCorretor: 0,
  ir: 0,
  totalCustosVenda: 0,  
  totalInvestido: 0,
  lucroLiquido: 0,
  tipoFinanciamento: "SAC",
  totalPagoParcelas: 0,
  saldoDevedor: 0
};